version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/backend/app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "npm"
    directory: "/frontend/app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
