version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/infrastructure"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ⬆
