services:
  backend:
    build:
      context: ./backend
      target: dev
    networks:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./backend/app
        target: /app
  frontend:
    build:
      context: ./frontend
      target: dev
    networks:
      - frontend
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend/app
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules/
    depends_on:
      - backend

networks:
  backend:
  frontend:

volumes:
  node_modules:
