services:
  backend:
    image: "${BACKEND_IMAGE}"
    build:
      context: ./backend
      target: dev
    networks:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./backend/app
        target: /opt/app
  frontend:
    image: "${FRONTEND_IMAGE}"
    build:
      context: ./frontend
      target: dev
    networks:
      - frontend
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend/app
        target: /opt/app
      # Ignore node_modules from the host when using bind mounts by applying the named volume
      - type: volume
        source: node_modules
        target: /opt/app/node_modules
    depends_on:
      - backend

networks:
  backend:
  frontend:

volumes:
  node_modules:
