name: Build Proxy
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  set-context:
    name: Set context
    runs-on: ubuntu-latest
    outputs:
      prod-image: ${{ steps.set-variables.outputs.prod-image }}
      registry: ${{ steps.set-variables.outputs.registry }}

    steps:
      - id: set-variables
        name: Set variables
        run: |
          registry=059132655198.dkr.ecr.eu-central-1.amazonaws.com
          echo "prod-image=$registry/proxy-3692f6f" >> $GITHUB_OUTPUT
          echo "registry=$registry" >> $GITHUB_OUTPUT

  call-build-push-final-image:
    name: Build and Push final image
    needs: [set-context]
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: proxy
      context: "{{defaultContext}}:proxy"
      images: ${{ needs.set-context.outputs.prod-image }}
      registry: ${{ needs.set-context.outputs.registry }}
      tags: |
        type=semver,pattern={{version}}
    secrets:
      registry-username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      registry-password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
