name: Build and Push Docker image
on:
  workflow_call:
    inputs:
      cache-key:
        description: Key that is used together with the target to define the cache scope
        type: string
        required: true
      context:
        description: Docker context (path) to start build from
        type: string
      target:
        description: Target stage to build
        type: string
      images:
        description: List of Docker images to use as base name for tags
        type: string
        default: |
          ghcr.io/${{ github.repository }}
      tags:
        description: List of tags as key-value pair attributes in CSV format
        type: string
        default: |
          type=raw,value=${{ github.run_id }}
      platforms:
        description: List of target platforms for build
        type: string
        default: |
          linux/amd64
jobs:
  build-push-image:
    name: Build and Push image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: ${{ inputs.tags }}

      - name: Build and Push image
        uses: docker/build-push-action@v4
        env:
          CACHE_SCOPE: ${{ inputs.target && format('{0}-{1}', inputs.cache-key, inputs.target) || inputs.cache-key }}
        with:
          push: true
          context: ${{ inputs.context }}
          target: ${{ inputs.target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ env.CACHE_SCOPE }}
          cache-to: type=gha,mode=max,scope=${{ env.CACHE_SCOPE }}
          platforms: ${{ inputs.platforms }}
