name: Deploy
on:
  workflow_dispatch:
inputs:
  version:
    type: string
    description: Deployment version
jobs:
  set-context:
    name: Set context
    runs-on: ubuntu-latest
    outputs:
      backend-image: ${{ steps.set-variables.outputs.backend-image }}
      frontend-image: ${{ steps.set-variables.outputs.frontend-image }}
      proxy-image: ${{ steps.set-variables.outputs.proxy-image }}
      registry: ${{ steps.set-variables.outputs.registry }}

    steps:
      - id: set-variables
        name: Set variables
        run: |
          registry=059132655198.dkr.ecr.eu-central-1.amazonaws.com
          echo "registry=$registry" >> $GITHUB_OUTPUT
          echo "backend-image=$registry/backend-9119369" >> $GITHUB_OUTPUT
          echo "frontend-image=$registry/frontend-998092c" >> $GITHUB_OUTPUT
          echo "proxy-image=$registry/proxy-3692f6f" >> $GITHUB_OUTPUT

  call-build-push-backend-image:
    name: Build and Push backend image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: backend
      context: "{{defaultContext}}:backend"
      images: ${{ needs.set-context.outputs.backend-image }}
      registry: ${{ needs.set-context.outputs.registry }}
      tags: |
        type=raw,value=${{ github.event.inputs.version }}
    secrets:
      registry-username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      registry-password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-build-push-frontend-image:
    name: Build and Push frontend image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: frontend
      context: "{{defaultContext}}:frontend"
      images: ${{ needs.set-context.outputs.frontend-image }}
      registry: ${{ needs.set-context.outputs.registry }}
      tags: |
        type=raw,value=${{ github.event.inputs.version }}
    secrets:
      registry-username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      registry-password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-build-push-proxy-image:
    name: Build and Push proxy image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: proxy
      context: "{{defaultContext}}:proxy"
      images: ${{ needs.set-context.outputs.proxy-image }}
      registry: ${{ needs.set-context.outputs.registry }}
      tags: |
        type=raw,value=${{ github.event.inputs.version }}
    secrets:
      registry-username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      registry-password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
