name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Restore pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          load: true
          context: "{{defaultContext}}:backend"
          target: dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          load: true
          context: "{{defaultContext}}:frontend"
          target: dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Run linter
        run: pre-commit run --all-files --show-diff-on-failure
        shell: bash
