name: Run E2E Tests
on:
  pull_request:
    paths:
      - backend/**
      - frontend/**
      - proxy/**
      - e2e/**
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  set-context:
    name: Set context
    runs-on: ubuntu-latest
    outputs:
      backend-image: ${{ steps.set-variables.outputs.backend-image }}
      frontend-image: ${{ steps.set-variables.outputs.frontend-image }}
      proxy-image: ${{ steps.set-variables.outputs.proxy-image }}
      e2e-image: ${{ steps.set-variables.outputs.e2e-image }}

    steps:
      - id: set-variables
        name: Set variables
        run: |
          echo "backend-image=ghcr.io/przemoo16/project-starter-graphql-backend" >> $GITHUB_OUTPUT
          echo "frontend-image=ghcr.io/przemoo16/project-starter-graphql-frontend" >> $GITHUB_OUTPUT
          echo "proxy-image=ghcr.io/przemoo16/project-starter-graphql-proxy" >> $GITHUB_OUTPUT
          echo "e2e-image=ghcr.io/przemoo16/project-starter-graphql-e2e" >> $GITHUB_OUTPUT

  call-build-push-backend-image:
    name: Build and Push backend image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: backend
      context: "{{defaultContext}}:backend"
      images: ${{ needs.set-context.outputs.backend-image }}
      registry: ghcr.io
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  call-build-push-frontend-image:
    name: Build and Push frontend image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: frontend
      context: "{{defaultContext}}:frontend"
      images: ${{ needs.set-context.outputs.frontend-image }}
      registry: ghcr.io
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  call-build-push-proxy-image:
    name: Build and Push proxy image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: proxy
      context: "{{defaultContext}}:proxy"
      images: ${{ needs.set-context.outputs.proxy-image }}
      registry: ghcr.io
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  call-build-push-e2e-image:
    name: Build and Push e2e image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: e2e
      context: "{{defaultContext}}:e2e"
      images: ${{ needs.set-context.outputs.e2e-image }}
      registry: ghcr.io
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run e2e tests
    runs-on: ubuntu-latest
    needs:
      [
        set-context,
        call-build-push-backend-image,
        call-build-push-frontend-image,
        call-build-push-proxy-image,
        call-build-push-e2e-image,
      ]

    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          BACKEND_IMAGE=${{ needs.set-context.outputs.backend-image }}:${{ needs.call-build-push-backend-image.outputs.image-tag }} \
          FRONTEND_IMAGE=${{ needs.set-context.outputs.frontend-image }}:${{ needs.call-build-push-frontend-image.outputs.image-tag }} \
          PROXY_IMAGE=${{ needs.set-context.outputs.proxy-image }}:${{ needs.call-build-push-proxy-image.outputs.image-tag }} \
          E2E_IMAGE=${{ needs.set-context.outputs.e2e-image }}:${{ needs.call-build-push-e2e-image.outputs.image-tag }} \
          make e2e-test
        shell: bash
