name: Test Backend
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  call-build-push-image:
    name: Build and Push image

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: backend
      context: "{{defaultContext}}:backend"
      target: dev
      images: ghcr.io/przemoo16/project-starter-graphql-backend

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [call-build-push-image]

    permissions:
      packages: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: docker run --rm ghcr.io/przemoo16/project-starter-graphql-backend:${{ needs.call-build-push-image.outputs.image-tag }} pytest .
        shell: bash

  call-scan-image:
    name: Scan image
    needs: [call-build-push-image]

    permissions:
      packages: read

    uses: ./.github/workflows/scan-image.yaml
    with:
      image: ghcr.io/przemoo16/project-starter-graphql-backend:${{ needs.call-build-push-image.outputs.image-tag }}
