name: Test Backend
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  call-build-image:
    name: Build image

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-image.yaml
    with:
      cache-key: backend-test
      context: "{{defaultContext}}:backend"
      tags: ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }}
      target: test

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [call-build-image]

    permissions:
      packages: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: docker run --rm ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }} pytest .
        shell: bash

  call-scan-image:
    name: Scan image
    needs: [call-build-image]

    permissions:
      packages: read

    uses: ./.github/workflows/scan-image.yaml
    with:
      image: ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }}
