name: Test Docker image
on:
  workflow_call:
    inputs:
      command:
        description: Test command to run
        required: true
        type: string
jobs:
  test-image:
    name: Test image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: ${{ inputs.command }}
        shell: bash
