name: Test Backend
on:
  pull_request:
    paths:
      - backend/**
jobs:
  set-context:
    name: Set context
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-variables.outputs.image }}

    steps:
      - id: set-variables
        name: Set variables
        run: |
          echo "image=ghcr.io/przemoo16/project-starter-graphql-backend" >> $GITHUB_OUTPUT

  build-push-image:
    name: Build and push image
    needs: [set-context]

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: backend
      context: "{{defaultContext}}:backend"
      target: dev
      images: ${{ needs.set-context.outputs.image }}
      registry: ghcr.io
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  run-unit-tests:
    name: Run unit tests
    needs: [set-context, build-push-image]

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/test-image.yaml
    with:
      command: BACKEND_IMAGE=${{ needs.set-context.outputs.image }}:${{ needs.build-push-image.outputs.image-tag }} make unit-test-backend

  run-integration-tests:
    name: Run integration tests
    needs: [set-context, build-push-image]

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/test-image.yaml
    with:
      command: BACKEND_IMAGE=${{ needs.set-context.outputs.image }}:${{ needs.build-push-image.outputs.image-tag }} make integration-test-backend

  scan-image:
    name: Scan image
    needs: [set-context, build-push-image]

    permissions:
      packages: read

    uses: ./.github/workflows/scan-image.yaml
    with:
      image: ${{ needs.set-context.outputs.image }}:${{ needs.build-push-image.outputs.image-tag }}
