name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Restore pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run linter
        run: pre-commit run --all-files --show-diff-on-failure
        shell: bash

  build-test-image:
    name: Build Docker image for testing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  run-unit-tests:
    name: Run unit tests
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: docker run --rm ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }} pytest .
        shell: bash

  scan-image:
    name: Scan Image with Trivy
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image to scan
        run: docker pull ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }}
        shell: bash

      - name: Run Trivy vulnerability scanner (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }}
          format: table

      - name: Run Trivy vulnerability scanner (blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/przemoo16/project-starter-graphql-backend:${{ github.run_id }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
