name: Test Frontend
on:
  pull_request:
    paths:
      - frontend/**
  push:
    branches:
      - main
    paths:
      - frontend/**
jobs:
  call-build-push-image:
    name: Build and Push image

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: frontend
      context: "{{defaultContext}}:frontend"
      target: dev
      images: ghcr.io/przemoo16/project-starter-graphql-frontend

  call-test-image-unit:
    name: Run unit tests
    needs: [call-build-push-image]

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/test-image.yaml
    with:
      command: make unit-test-frontend

  call-scan-image:
    name: Scan image
    needs: [call-build-push-image]

    permissions:
      packages: read

    uses: ./.github/workflows/scan-image.yaml
    with:
      image: ghcr.io/przemoo16/project-starter-graphql-frontend:${{ needs.call-build-push-image.outputs.image-tag }}
