name: Test Backend
on:
  pull_request:
    paths:
      - backend/**
  push:
    branches:
      - main
    paths:
      - backend/**
jobs:
  call-build-push-image:
    name: Build and Push image

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-push-image.yaml
    with:
      cache-key: backend
      context: "{{defaultContext}}:backend"
      target: dev
      images: ghcr.io/przemoo16/project-starter-graphql-backend

  call-test-image-unit:
    name: Run unit tests
    needs: [call-build-push-image]

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/test-image.yaml
    with:
      command: make unit-test-backend

  call-test-image-integration:
    name: Run integration tests
    needs: [call-build-push-image]

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/test-image.yaml
    with:
      command: make integration-test-backend

  call-scan-image:
    name: Scan image
    needs: [call-build-push-image]

    permissions:
      packages: read

    uses: ./.github/workflows/scan-image.yaml
    with:
      image: ghcr.io/przemoo16/project-starter-graphql-backend:${{ needs.call-build-push-image.outputs.image-tag }}
